#-------------------------------------------#
#		Makefile for Unix systems			#
#	using a GNU C compiler					#
#-------------------------------------------#

CC=gcc
CFLAGS=-g	# Compiler flags: -g	-- Enable debugging
7.1-calc1: 7.1-calc1.c
			$(CC) $(CFLAGS) -o 7.1-calc1 7.1-calc1.c
clean:
		rm -f 7.1-calc1
